application:
  appName: usuarioservice

  mail:
    endereco-remetente: doceria.pis@gmail.com
    nome-remetente: doceria

spring:
  application:
    name: usuarioservice

    cloud:
      stream:
        bindings:
          mailer:
            destination: mailer

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/pis
    username: pis
    password: pis

    hikari:
      poolName: Hikari
      auto-commit: false

  jackson:
    date-format: yyyy-MM-dd
    deserialization:
      fail-on-unknown-properties: false

  jpa:
    hibernate:
      ddl-auto: update
    database: POSTGRESQL
    show-sql: true
    open-in-view: false
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false

  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: doceria.pis@gmail.com
    password: doceriapis11
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          quitwait: false

server:
  port: 8080